services:
  mysql:
    image: mysql:8.0
    container_name: meteorologia_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: estacionmeteo25-26
      MYSQL_USER: Meteo1
      MYSQL_PASSWORD: Meteo1
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./Base_de_datos/:/docker-entrypoint-initdb.d/
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: meteorologia_phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8080:80"
    depends_on:
      mysql:
        condition: service_healthy

  php-app:
    build: .
    container_name: meteorologia_php
    restart: always
    environment:
      - WEB_DOCUMENT_ROOT=/app/public
      - APP_ENV=development
      - APP_DEBUG=true
    ports:
      - "8082:80"
    volumes:
      - ./:/app
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  mysql_data:
