# Usa la imagen oficial de Grafana como base
FROM grafana/grafana:latest

# Variables de entorno para la subruta
ENV GF_SERVER_ROOT_URL="%(protocol)s://%(domain)s/grafana/"
ENV GF_SERVER_SERVE_FROM_SUB_PATH="true"

# Expone el puerto 3000
EXPOSE 3000

# Comando por defecto (ya viene en la imagen oficial)
CMD ["/run.sh"]
