networks:
  frontend:
    name: frontend
  backend:
    name: backend

services:
  # --- AUTOMATED REVERSE PROXY ---
  nginx-proxy:
    image: nginxproxy/nginx-proxy:${NGINX_PROXY_VERSION}
    container_name: nginx-proxy
    labels:
      - com.github.nginx-proxy.nginx=true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
    networks:
      - frontend
      - backend
    restart: always

  # --- MANAGEMENT ---
  portainer:
    image: portainer/portainer-ce:${PORTAINER_VERSION}
    container_name: portainer
    command: -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    environment:
      - VIRTUAL_HOST=portainer-victor.${MAIN_DOMAIN}
      - VIRTUAL_PORT=9000
    networks:
      - frontend
    restart: unless-stopped

  # --- MONITORING ---
  prometheus:
    image: prom/prometheus:${PROMETHEUS_VERSION}
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    environment:
      - VIRTUAL_HOST=prometheus-victor.${MAIN_DOMAIN}
      - VIRTUAL_PORT=9090
    networks:
      - backend
      - frontend
    restart: unless-stopped

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    networks:
      - backend
    restart: unless-stopped

  grafana:
    image: grafana/grafana:${GRAFANA_VERSION}
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - VIRTUAL_HOST=grafana-victor.${MAIN_DOMAIN}
      - VIRTUAL_PORT=3000
    networks:
      - frontend
      - backend
    restart: unless-stopped

volumes:
  portainer_data:
  grafana_data:
  prometheus_data:
  vhost:
  html:
